# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd3533d6a5b56859fdf15f8c6e2c53f63bbbc37e7539f72cc62581c11417c4156dfa68361c78dfacf97f7b5856213d5f3ee84aa04b5ecdadeaa5299b84f8a141

test:
  secret_key_base: 462d7aac2e8545dceb6cdb30948c79bcebd9c918467b6be6d4052d706797c5651d4ef763ad219517aa7e119b621307340628d3bb7ead4bb42aa353afbfcc3a7c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
